"""Shared pytest fixtures for the grounding test suite.

Builds (or reuses) the fixture ZIM at test-collection time so every test
module can reference it.  The ZIM is ~36 KB; it is built programmatically from
synthetic articles and is NOT committed as a binary — it is regenerated by the
build script if absent.
"""

from __future__ import annotations

import pathlib
import sys

import pytest

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
FIXTURE_DIR = REPO_ROOT / "tests" / "fixtures"
FIXTURE_ZIM = FIXTURE_DIR / "test_fixture.zim"

# Ensure the grounding src package is importable when running tests directly
sys.path.insert(0, str(REPO_ROOT / "src"))


def _ensure_fixture_zim() -> pathlib.Path:
    """Build the fixture ZIM if it does not exist."""
    if not FIXTURE_ZIM.exists():
        build_script = FIXTURE_DIR / "build_fixture_zim.py"
        import importlib.util

        spec = importlib.util.spec_from_file_location("build_fixture_zim", build_script)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        mod.build(FIXTURE_ZIM)
    return FIXTURE_ZIM


@pytest.fixture(scope="session")
def fixture_zim_path() -> pathlib.Path:
    """Path to the tiny test fixture ZIM."""
    return _ensure_fixture_zim()


@pytest.fixture(scope="session")
def vikidia_anchor() -> str:
    """Anchor URL for the Fraction article (vikidia-style)."""
    return "https://en.vikidia.org/wiki/Fraction"


@pytest.fixture(scope="session")
def simple_wiki_anchor() -> str:
    """Anchor URL for the Division article (simple.wikipedia.org-style)."""
    return "https://simple.wikipedia.org/wiki/Division_(mathematics)"


@pytest.fixture
def grounding_cfg(fixture_zim_path, tmp_path) -> dict:
    """A minimal grounding config block pointing at the fixture ZIM."""
    return {
        "zim_dir": str(fixture_zim_path.parent),
        "sources": {
            "vikidia": fixture_zim_path.name,
            "wikipedia_simple": fixture_zim_path.name,
        },
        "max_passage_chars": 1200,
        "cache": {"enabled": False},
    }
