"""Item bank — authored, checkable (problem, answer) items keyed by curriculum node.

Why this exists: the FSM presents questions and then scores the child's answer with the
deterministic verifier (verify_numeric).  That needs a GROUND-TRUTH answer.  LLM-invented
questions have none — so checkable questions are drawn from this bank instead, keeping the
verifier authoritative and the LLM out of the correctness path (see
docs/PHASE0_STATUS.md W1.5/W3 notes).

The bank is generated by scripts/build_itembank.py from the eval transfer suite.
Pilot scope = a finite authored bank (Option A); a parametric generator (Option B) is the
scalable follow-up.

Public API:
    Item                       — one checkable item
    ItemBank.sample(node_id)   — a fresh item for a node (no-repeat until the pool is exhausted)
    load_item_bank(path)       — build an ItemBank from a jsonl file
"""

from __future__ import annotations

import json
import random
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Item:
    id: str
    node: str
    problem: str          # child-facing question text (presented verbatim)
    answer: str           # ground truth for the verifier
    answer_type: str      # int | fraction | mc4 | free_text
    checker: str          # int_exact | fraction_equiv | mc_choice | none
    # mc4 only: choice texts in A/B/C/D order (STRUCTURED — the web view renders
    # these as radio buttons instead of parsing them back out of the problem
    # string). None for non-choice items; the problem text may still carry the
    # inline "A) … B) …" form for the CLI/transcript.
    choices: tuple[str, ...] | None = None
    # mc4 only: the question WITHOUT the inline "A) … B) …" options (R2.1) — the
    # web view renders this + the radio choices, so the options never appear
    # twice. None for non-choice items; `problem` keeps the full inline form for
    # CLI/transcript surfaces that have no radios.
    stem: str | None = None


class ItemBank:
    """In-memory pool of checkable items, grouped by node.

    sample() returns items without replacement per node (shuffled), reshuffling once a
    node's pool is exhausted so a long session keeps getting items.  Stateful by design;
    construct one per session (like the SessionController).
    """

    def __init__(self, items: list[Item], rng: random.Random | None = None) -> None:
        self._by_node: dict[str, list[Item]] = {}
        for it in items:
            self._by_node.setdefault(it.node, []).append(it)
        self._rng = rng or random.Random()
        self._queue: dict[str, list[Item]] = {}  # remaining (shuffled) items per node

    def has(self, node_id: str) -> bool:
        return bool(self._by_node.get(node_id))

    def sample(self, node_id: str) -> Item | None:
        """Return a fresh item for *node_id*, or None if the node has no items."""
        pool = self._by_node.get(node_id)
        if not pool:
            return None
        queue = self._queue.get(node_id)
        if not queue:
            queue = list(pool)
            self._rng.shuffle(queue)
            self._queue[node_id] = queue
        return queue.pop()

    def example(self, node_id: str, exclude_id: str | None = None) -> Item | None:
        """A stable solved example for a node WITHOUT consuming the sample queue.

        Used to fill a worked-example slot in Help prompts. Excludes *exclude_id* (the live
        question) so we don't reveal its answer; falls back to the first authored item.
        """
        pool = self._by_node.get(node_id)
        if not pool:
            return None
        for it in pool:
            if it.id != exclude_id:
                return it
        return pool[0]

    def __len__(self) -> int:
        return sum(len(v) for v in self._by_node.values())


def load_item_bank(path: str | Path, rng: random.Random | None = None) -> ItemBank:
    """Load an item bank from a jsonl file (one Item per line)."""
    p = Path(path)
    items: list[Item] = []
    for line in p.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        d = json.loads(line)
        items.append(Item(
            id=d["id"],
            node=d["node"],
            problem=d["problem"],
            answer=str(d["answer"]),
            answer_type=d.get("answer_type", "free_text"),
            checker=d.get("checker", "none"),
            choices=tuple(d["choices"]) if d.get("choices") else None,
            stem=d.get("stem"),
        ))
    return ItemBank(items, rng=rng)
